version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
    command: ["npm", "run", "worker"]
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  redis:
    image: "redis:7-alpine" # Use a lightweight Redis image
    ports:
      - "6379:6379" # Map the host's 6379 port to the container's 6379