services:
  redis:
    image: "redis:7-alpine" # Use a lightweight Redis image
    ports:
      - "6379:6379" # Map the host's 6379 port to the container's 6379
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - redis
    volumes:
      - job_files:/app/uploads 

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    volumes:
      - job_files:/app/uploads 

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  redis_data:
  job_files: 